[package]
name = "err-tree"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
anyhow = { workspace = true, optional = true }
indent_write.workspace = true

[features]
anyhow-compat = ["dep:anyhow"]
